name: CI
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint-and-test:
    name: Lint and Test (Python ${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
      - name: Ruff (lint)
        run: ruff check .
      - name: Black (format check)
        run: black --check .
      - name: isort (import order check)
        run: isort --check-only .
      - name: mypy (type check)
        run: mypy .
      - name: Pytest
        run: python -m pytest -q

  smoke-e2e-probe:
    name: Smoke test e2e probe
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install and build front-end
        working-directory: front-end
        run: |
          npm ci
          npm run build
      - name: Copy front-end build into add-on package
        run: |
          mkdir -p canvas3d/ui/frontend
          cp -r front-end/dist/* canvas3d/ui/frontend
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: |
            pyproject.toml
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
      - name: Compile e2e probe
        run: python -m py_compile tools/e2e_llm_probe.py
      - name: Run e2e probe (mock mode)
        env:
          CANVAS3D_MOCK_MODE: "1"
        run: python tools/e2e_llm_probe.py --count 1 --timeout 1
